services:

  front:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/webapp
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  back:
    build: ./backend
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    environment:
      WDS_SOCKET_HOST: 127.0.0.1
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      THEGOODCORNER_DBPASS: ${DBPASS}

  db:
    image: postgres:16
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - "5432:5432"
    volumes: 
      - /c/Users/luism/OneDrive/Documents/Openclassrooms/Assofac DWWM/the-good-corner-db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

